* Add command line interface options (ifup -o foo=bar eth1). Yay! * Switch to using iproute instead of ifconfig//route. Thanks to Andrew   Pollock. * Drop support for kernels prior to 2.1.100 (and that don't have NETLINK   for iproute). * Drop support for specifying a netmask in static inet interfaces. * Bump DH_COMPAT to 4 (from 1!)

diff --git a/debian/testbuild b/debian/testbuild
--- a/debian/testbuild
+++ b/debian/testbuild
@@ -2,7 +2,6 @@
 
 rm -rf tests/
 mkdir tests
-
 cat >tests/testcase.1 <<EOF
 # RUN: -a
 auto eth0
@@ -17,8 +16,8 @@ cat >tests/up.1 <<EOF
 ====stderr====
 Configuring interface eth0=eth0 (inet)
 run-parts --verbose /etc/network/if-pre-up.d
-
-ifconfig eth0 1.2.3.4 netmask 255.255.255.0  	 up
+ip addr add 1.2.3.4  	 dev eth0
+ip link set dev eth0   up
 
 echo hi
 echo hello
@@ -60,41 +59,42 @@ cat >tests/up.2 <<EOF
 ====stderr====
 Configuring interface eth0=eth0 (inet)
 run-parts --verbose /etc/network/if-pre-up.d
-
-ifconfig eth0 1.2.3.4 netmask 255.255.255.0  	 up
+ip addr add 1.2.3.4  	 dev eth0
+ip link set dev eth0   up
 
 run-parts --verbose /etc/network/if-up.d
 Configuring interface eth1=eth1 (inet)
 run-parts --verbose /etc/network/if-pre-up.d
-
-ifconfig eth1 1.3.4.5 netmask 255.255.255.0  	 up
+ip addr add 1.3.4.5  	 dev eth1
+ip link set dev eth1   up
 
 run-parts --verbose /etc/network/if-up.d
 Configuring interface eth2=eth2 (inet)
 run-parts --verbose /etc/network/if-pre-up.d
-
-ifconfig eth2 1.4.5.6 netmask 255.255.255.0  	 up
+ip addr add 1.4.5.6  	 dev eth2
+ip link set dev eth2   up
 
 run-parts --verbose /etc/network/if-up.d
 Configuring interface eth3=eth3 (inet)
 run-parts --verbose /etc/network/if-pre-up.d
-
-ifconfig eth3 1.5.6.7 netmask 255.255.255.0  	 up
+ip addr add 1.5.6.7  	 dev eth3
+ip link set dev eth3   up
 
 run-parts --verbose /etc/network/if-up.d
 Configuring interface eth4=eth4 (inet)
 run-parts --verbose /etc/network/if-pre-up.d
-
-ifconfig eth4 1.7.8.9 netmask 255.255.255.0  	 up
+ip addr add 1.7.8.9  	 dev eth4
+ip link set dev eth4   up
 
 run-parts --verbose /etc/network/if-up.d
 Configuring interface eth5=eth5 (inet)
 run-parts --verbose /etc/network/if-pre-up.d
-
-ifconfig eth5 1.8.9.10 netmask 255.255.255.0  	 up
+ip addr add 1.8.9.10  	 dev eth5
+ip link set dev eth5   up
 
 run-parts --verbose /etc/network/if-up.d
 EOF
+
 cat >tests/testcase.3 <<EOF
 # RUN: -a
 auto eth0
@@ -110,8 +110,8 @@ cat >tests/up.3 <<EOF
 ====stderr====
 Configuring interface eth0=eth0 (inet)
 run-parts --verbose /etc/network/if-pre-up.d
-
-ifconfig eth0 1.2.3.4 netmask 255.255.255.0             up
+ip addr add 1.2.3.4  	 dev eth0
+ip link set dev eth0   up
 
 run-parts --verbose /etc/network/if-up.d
 Configuring interface eth0=eth0 (inet6)
@@ -137,39 +137,38 @@ cat >tests/up.4 <<EOF
 ====stderr====
 Configuring interface eth0=work (inet)
 run-parts --verbose /etc/network/if-pre-up.d
-
-ifconfig eth0 1.2.3.4 netmask 255.255.255.0  	 up
+ip addr add 1.2.3.4  	 dev eth0
+ip link set dev eth0   up
 
 echo hi
 echo hello
 run-parts --verbose /etc/network/if-up.d
 EOF
 
-
 result=true
 for test in 1 2 3 4; do
-	args="$(cat tests/testcase.$test | sed -n 's/^# RUN: //p')"
-	./ifup -nv --force -i tests/testcase.$test $args \
-		>tests/up-res-out.$test 2>tests/up-res-err.$test || 
-		true
-	(echo "====stdout===="; cat tests/up-res-out.$test
-	 echo "====stderr===="; cat tests/up-res-err.$test) > tests/up-res.$test
+        args="$(cat tests/testcase.$test | sed -n 's/^# RUN: //p')"
+        ./ifup -nv --force -i tests/testcase.$test $args \
+                >tests/up-res-out.$test 2>tests/up-res-err.$test || 
+                true
+        (echo "====stdout===="; cat tests/up-res-out.$test
+         echo "====stderr===="; cat tests/up-res-err.$test) > tests/up-res.$test
 
-	echo "Testcase $test: $args"
-	
-	if diff -ub tests/up.$test tests/up-res.$test; then
-		echo "(okay)"
-	else
-		echo "(failed)"
-		result=false
-	fi
-	echo "=========="
+        echo "Testcase $test: $args"
+        
+        if diff -ub tests/up.$test tests/up-res.$test; then
+                echo "(okay)"
+        else
+                echo "(failed)"
+                result=false
+        fi
+        echo "=========="
 done
 
 if $result; then
-	echo "(okay overall)"
-	exit 0
+        echo "(okay overall)"
+        exit 0
 else
-	echo "(failed overall)"
-	exit 1
+        echo "(failed overall)"
+        exit 1
 fi
